---

- name: "Remove existing crons"
  cron: name="{{item.name}}" state=absent
  with_items:
    - {name: "Mongo Backup"}
  ignore_errors: True

- name: "Setup crons"
  cron: name="{{item.name}}" minute="{{item.minute}}" hour="{{item.hour}}" job="{{item.job}}"
  with_items:
    - {name: "Mongo Backup", minute: "0", hour: "10", job: "{{ script_dir }}/mongodb_backup.sh"}
