---

- name: "Remove existing crons"
  cron: name="Mongo Backup" state=absent
  ignore_errors: True

- name: "Setup crons"
  cron: name="{{item.name}}" minute="{{item.minute}}" hour="{{item.hour}}" day="{{item.day}}" month="{{item.month}}" weekday="{{item.weekday}}" job="{{item.job}}"
  with_items:
    - {name: "Mongo Backup", minute: "{{ cron_minute }}", hour: "{{ cron_hour }}", day: "{{ cron_day }}", month: "{{ cron_month }}", weekday: "{{ cron_weekday }}", job: "{{ script_dir }}/mongodb_backup.sh {{ backup_script_params }}"}

