---

- name: "Install apt packages"
  apt: name={{ item }} state=present
  with_items: "{{ packages_required }}"
  when: ansible_os_family == "Debian"
  become: True

- name: "Install yum packages"
  yum: name={{ item }} state=present
  with_items: "{{ packages_required }}"
  when: ansible_os_family == "RedHat"
  become: True

- name: "Install zypper packages"
  zypper: name={{ item }} state=present
  with_items: "{{ packages_required }}"
  when: ansible_os_family == "Suse"
  become: True

- name: "Install tinys3"
  command: "sudo pip install -U boto"
  become: True
